---
title: '2023 30-day Map Challenge • Day 22 • North is Not Always Up'
author: 'Ryan Peek'
execute:
  echo: false
  warning: false
  message: false
format: 
  html:
    self-contained: true
    code-overflow: wrap
    code-fold: true
    code-tools: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    theme: journal #litera #default
    highlight-style: arrow
editor_options: 
  chunk_output_type: console
---

## North is Not Always Up

orientation of rivers use existing code

## Data

```{r}
#| label: the-data
#| message: false
#| warning: false
#| echo: true
#| eval: false

# CODE ADAPTED FROM
# https://github.com/USGS-VIZLAB/chart-challenge-22/tree/main/11_circular_lkoenig
# @lkoenig
# BY R. PEEK, 2022-04-12

library(tidyverse)
library(hrbrthemes)
library(janitor)
library(glue)
library(patchwork)
library(nhdplusTools)
library(sf)
library(ggspatial)
library(tigris)
options(tigris_use_cache = TRUE)
library(showtext)
library(colorspace)

# Source helper functions
source("code/f_orientation_helpers.R")

# Set up fonts for plots
font_add_google("Hepta Slab")

# Define huc8 sub-basins
# note: HUC8 subsets from the watershed boundary dataset (WBD) were used for
# convenience for this river orientation visualization, to represent a reasonable,
# "medium" scale of analysis and so that a user wouldn't need to have the national
# hydrography dataset (NHDPlusv2) downloaded locally. The selected HUC8 id's
# represent 'whole' watersheds/river networks, but not all HUC8 subsets do (i.e.,
# they may represent just a portion of a watershed).
huc8_tbl <- tibble(huc8_id = c("18020121", "18090208"),
                   huc8_name = c("North Fork Feather","Mojave"))

# Fetch NHDv2 flowlines for each huc8 basin
flines <- lapply(huc8_tbl$huc8_id, fetch_flowlines)

# Estimate channel orientation (i.e., azimuth) for each huc8 basin
flines_azimuth <- lapply(flines, function(x){
  az_df <- x %>%
    split(., 1:length(.$geometry)) %>%
    purrr::map_dfr(~mutate(., azimuth = calc_azimuth_circ_mean(.)))
  return(az_df)
})

# Format channel orientation table
flines_azimuth_df <- do.call("rbind", flines_azimuth) %>%
  select(huc8_id, azimuth, streamorde, lengthkm) %>%
  # add huc8 name to this table
  left_join(huc8_tbl, by = "huc8_id") %>%
  # define order of huc8's
  mutate(huc8_name_ord = factor(huc8_name,
                           levels = c("North Fork Feather",
                                      "Mojave"))) %>%
  relocate(geometry, .after = last_col())

# Assemble plot

# A couple steps so that coord_polar will allow free scales for facets,
# grabbed from https://github.com/tidyverse/ggplot2/issues/2815
cp <- coord_polar()
cp$is_free <- function() TRUE

# Create grid containing channel orientation plots
azimuth_grid <- plot_azimuth(flines_azimuth_df,
                             cp, fill = "#105073", color = "#09344E") +
  facet_wrap(~huc8_name_ord, scales = "free_y", ncol = 4) +
  theme(text = element_text(size = 20),
        strip.text.x = element_text(size = 20, face = "bold"),
        plot.background = element_blank(),
        panel.background = element_blank(),
        aspect.ratio = 1,
        panel.grid = element_line(size = 0.2),
        axis.text.x = element_text(size = 20))
azimuth_grid

# Save plots
ggsave(glue::glue("figs/day22-azimuth_grid.png"),
       plot = azimuth_grid,bg = "white",
       width = 12, height = 12, units = c("in"),
       dpi = 300)


# Mojave -------------------------------------------------------------

# Create "legend" inset plot that explains how to read the polar histograms
inset_moj_plot <- plot_ntw(filter(flines_azimuth_df, huc8_name == "Mojave"))
inset_mpolar_plot <- plot_azimuth(filter(flines_azimuth_df,huc8_name == "Mojave"),
                                 fill = "#105073", color = "#09344E") +
  theme(plot.margin = unit(c(t=-4, r=15, b=-4, l=0), "lines"),
        text = element_text(colour = "white", size = 40),
        plot.background = element_blank(),
        axis.text = element_text(color="white"),
        panel.background = element_blank(),
        aspect.ratio = 1)

inset_plot1 <- inset_mpolar_plot + inset_element(inset_moj_plot, 0.6, 0.3, 1, 1, align_to = 'full') +
  plot_annotation(title = expression("The Mojave River (CA) generally flows in the"~bold("north")~"direction"),
                  subtitle = "from its headwaters in the desert of CA.",
                  caption = 'The direction of each bar in the polar histogram represents the river orientation and the\nlength of each bar represents the proportion of total river length with that orientation.',
                  theme = theme(plot.title = element_text(colour = "white",size = 20,
                                                          hjust = 0),
                                plot.subtitle = element_text(colour = "white",
                                                             size = 20, hjust = 0),
                                plot.caption = element_text(colour = "white",
                                                            size = 10, hjust = 0),
                                plot.background = element_rect(fill = "black", colour = "black"),
                                panel.background = element_rect(fill= "black", color="black"),
                                aspect.ratio = 1))
inset_plot1_final <- inset_plot1 + plot_compass(text_size = 11) + plot_annotation(theme=theme(plot.background = element_rect(fill = "black", colour = "black"),
        panel.background = element_rect(fill = "black", colour = "black")))
inset_plot1_final

#ggsave("figs/day22-azimuth-moj.png", inset_plot, bg="black",
#       width = 8, height = 6, units = c("in"), dpi = 300)

# NF Feather -------------------------------------------------------------

# Create "legend" inset plot that explains how to read the polar histograms
inset_nf_plot <- plot_ntw(filter(flines_azimuth_df, huc8_name == "North Fork Feather"))
inset_nfpolar_plot <- plot_azimuth(filter(flines_azimuth_df,huc8_name == "North Fork Feather"),
                                 fill = "#105073", color = "#09344E") +
  theme(plot.margin = unit(c(t=-4, r=15, b=-4, l=0), "lines"),
        text = element_text(colour = "white", size = 40),
        plot.background = element_blank(),
        axis.text = element_text(color="white"),
        panel.background = element_blank(),
        aspect.ratio = 1)

inset_plot2 <- inset_nfpolar_plot + inset_element(inset_nf_plot, 0.6, 0.4, 1, 1, align_to = 'full') +
  plot_annotation(title = "The NF Feather River (CA) generally flows in the",
                  subtitle = expression(~bold("southern")~"direction from its headwaters."),
                  caption = 'The direction of each bar in the polar histogram represents the river orientation and the\nlength of each bar represents the proportion of total river length with that orientation.',
                  theme = theme(plot.title = element_text(colour = "white",size = 20,
                                                          hjust = 0),
                                plot.subtitle = element_text(colour = "white",
                                                             size = 20, hjust = 0),
                                plot.caption = element_text(colour = "white",
                                                            size = 10, hjust = 0),
                                plot.background = element_rect(fill="black",colour = "black"),
                                panel.background = element_rect(fill="black", colour = "black"),
                                aspect.ratio = 1))
inset_plot2_final <- inset_plot2 + plot_compass(text_size = 11) + plot_annotation(theme=theme(plot.background = element_rect(fill = "black", colour = "black"),
        panel.background = element_rect(fill = "black", colour = "black")))
inset_plot2_final

#ggsave("figs/day22-azimuth-nff.png", inset_plot, bg="black",
#       width = 8, height = 6, units = c("in"), dpi = 300)


```

```{r}
# combine plots

library(patchwork)


gall <- inset_plot1_final /plot_spacer()/ inset_plot2_final +
  patchwork::plot_layout(widths = c(1.1,-0.2, 1.1)) +
  plot_annotation(theme=theme(plot.background = element_rect(fill = "black", colour = "black"),
                              panel.background = element_rect(fill = "black", colour = "black")))
gall

ggsave(gall, filename = glue("figs/day22-north-not-up.png"), width = 11, height = 8.5, dpi = 300, bg="black")
```

